### PR TITLE
Porting app into Rails and Rspec

### PR DESCRIPTION
**Pull request by ogonzal87**
{
"comfortability": 4,
"completeness": 4,
“comments: “I had problems testing my static_pages_spec.rb. For some reason, i was telling me that i had an undefined method 'visit' when i ran rspec. I could not figure out the cause. 
}

### CODE REVIEW

**Comment by ogonzal87** [comment]
@rgpass could not assign it to you for some reason...

**Comment by rgpass** [comment]
> I had problems testing my static_pages_spec.rb. For some reason, i was telling me that i had an undefined method 'visit' when i ran rspec. I could not figure out the cause.

`visit` is a Capybara method, which means that it is not set up properly. There were a couple of steps in that process -- we can discuss if you do not remember them.

**Comment by rgpass** [comment]
Not sure why this has been merged and closed. :(

**Comment by rgpass** [comment]
Tests look solid. Assuming it looks good on your screen, after we get your test suite to pass I'll give the :+1:

**Pull request merged**
